In [1]:
#Ejecutar 1r
import pandas as pd
import numpy as np

In [2]:
# ----------------------- Pregunta 2 ----------------------- 
celebdict={}
celebdict['names']=['Denzel','Lopez','Gaga','Hanks','Beyonce']
celebdict['age']=[67,51,32,69,35]
celebdict['gender']=['m','f','f','m','f']
celebdict['occup']=['actor','everything','singer','actor','singer']

In [3]:
# Convierte un diccionario a un dataframe "hoja de datos"
df=pd.DataFrame(celebdict)

In [7]:
# Muestra con se ven los datos
print(df)

   age gender    names       occup
0   67      m   Denzel       actor
1   51      f    Lopez  everything
2   32      f     Gaga      singer
3   69      m    Hanks       actor
4   35      f  Beyonce      singer

In [8]:
#¿Los datos se almacenan como números enteros, cadenas, listas o algo más?
#
df['age'].dtype
df.dtypes

age        int64
gender    object
names     object
occup     object
dtype: object

In [9]:
#Muestra las 5 primeras filas y los 3 primeros datos."
df.head() 
df.head(3)

   age gender   names       occup
0   67      m  Denzel       actor
1   51      f   Lopez  everything
2   32      f    Gaga      singer

In [10]:
#Muestra las 5 ultimas filas y los 3 ultimos datos.
df.tail() 
df.tail(3)

   age gender    names   occup
2   32      f     Gaga  singer
3   69      m    Hanks   actor
4   35      f  Beyonce  singer

In [11]:
# Devuelve una tupla que representa la dimensionalidad del DataFrame. 
#Tuple: Es una colección de objetos ordenados e inmutables.
df.shape

(5, 4)

In [12]:
#Las etiquetas de columna del DataFrame.
df.columns.values

array(['age', 'gender', 'names', 'occup'], dtype=object)

In [13]:
# información general sobre el dataframe creado
df.describe()

             age
count   5.000000
mean   50.800000
std    17.297399
min    32.000000
25%    35.000000
50%    51.000000
75%    67.000000
max    69.000000

In [14]:
#Muestra un resumen 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
age       5 non-null int64
gender    5 non-null object
names     5 non-null object
occup     5 non-null object
dtypes: int64(1), object(3)
memory usage: 240.0+ bytes

In [24]:
# ----------------------- Pregunta 3.c ----------------------- 
#Ejecutamos la "base de datos"
movies = pd.read_csv("movie_metadata.csv")

In [8]:
# Quitar valores nulos.

In [30]:
# ----------------------- Pregunta 3.d ----------------------- 
#Devuelve el número de filas y columnas en el marco de datos
movies.shape

(5043, 28)

In [16]:
#Muestra las  etiquetas de columna movies
movies.columns.values

array(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes',
       'actor_2_name', 'actor_1_facebook_likes', 'gross', 'genres',
       'actor_1_name', 'movie_title', 'num_voted_users',
       'cast_total_facebook_likes', 'actor_3_name',
       'facenumber_in_poster', 'plot_keywords', 'movie_imdb_link',
       'num_user_for_reviews', 'language', 'country', 'content_rating',
       'budget', 'title_year', 'actor_2_facebook_likes', 'imdb_score',
       'aspect_ratio', 'movie_facebook_likes'], dtype=object)

In [25]:
#Muestra información general sobre el dataframe movies.
movies.describe()

/home/cloudera/anaconda3/lib/python3.5/site-packages/numpy/lib/function_base.py:3834: RuntimeWarning: Invalid value encountered in percentile
  RuntimeWarning)

,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,gross,num_voted_users,cast_total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
count,4993.000000,5028.000000,4939.000000,5020.000000,5036.000000,4.159000e+03,5.043000e+03,5043.000000,5030.000000,5022.000000,4.551000e+03,4935.000000,5030.000000,5043.000000,4714.000000,5043.000000
mean,140.194272,107.201074,686.509212,645.009761,6560.047061,4.846841e+07,8.366816e+04,9699.063851,1.371173,272.770808,3.975262e+07,2002.470517,1651.754473,6.442138,2.220403,7525.964505
std,121.601675,25.197441,2813.328607,1665.041728,15020.759120,6.845299e+07,1.384853e+05,18163.799124,2.013576,377.982886,2.061149e+08,12.474599,4042.438863,1.125116,1.385113,19320.445110
min,1.000000,7.000000,0.000000,0.000000,0.000000,1.620000e+02,5.000000e+00,0.000000,0.000000,1.000000,2.180000e+02,1916.000000,0.000000,1.600000,1.180000,0.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,8.593500e+03,1411.000000,NaN,NaN,NaN,NaN,NaN,5.800000,NaN,0.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,3.435900e+04,3090.000000,NaN,NaN,NaN,NaN,NaN,6.600000,NaN,166.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,9.630900e+04,13756.500000,NaN,NaN,NaN,NaN,NaN,7.200000,NaN,3000.000000
max,813.000000,511.000000,23000.000000,23000.000000,640000.000000,7.605058e+08,1.689764e+06,656730.000000,43.000000,5060.000000,1.221550e+10,2016.000000,137000.000000,9.500000,16.000000,349000.000000

In [23]:
# Muestra un resumen del contenido de movies
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5043 entries, 0 to 5042
Data columns (total 29 columns):
color                        5024 non-null object
director_name                4939 non-null object
num_critic_for_reviews       4993 non-null float64
duration                     5028 non-null float64
director_facebook_likes      4939 non-null float64
actor_3_facebook_likes       5020 non-null float64
actor_2_name                 5030 non-null object
actor_1_facebook_likes       5036 non-null float64
gross                        4159 non-null float64
genres                       5043 non-null object
actor_1_name                 5036 non-null object
movie_title                  5043 non-null object
num_voted_users              5043 non-null int64
cast_total_facebook_likes    5043 non-null int64
actor_3_name                 5020 non-null object
facenumber_in_poster         5030 non-null float64
plot_keywords                4890 non-null object
movie_imdb_link              5043 non-null object
num_user_for_reviews         5022 non-null float64
language                     5031 non-null object
country                      5038 non-null object
content_rating               4740 non-null object
budget                       4551 non-null float64
title_year                   4935 non-null float64
actor_2_facebook_likes       5030 non-null float64
imdb_score                   5043 non-null float64
aspect_ratio                 4714 non-null float64
movie_facebook_likes         5043 non-null int64
net_profit                   3891 non-null float64
dtypes: float64(14), int64(3), object(12)
memory usage: 1.1+ MB

In [19]:
# Muestra las primeras 5 líneas de movies.
movies.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

In [20]:
# Muestra las primeras 3 líneas especifica de movies.
movies.head(3)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000

In [21]:
# Muestra luna tabla que informa:
#Los dos puntos quiere decir que se seleciionan todas las filas.
# y el 11:19 muestra los datos de las posiciones del 11 al 19
movies.iloc[:,11:19].head()

,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,facenumber_in_poster,plot_keywords,movie_imdb_link,num_user_for_reviews
0,Avatar,886204,4834,Wes Studi,0.0,avatar|future|marine|native|paraplegic,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,3054.0
1,Pirates of the Caribbean: At World's End,471220,48350,Jack Davenport,0.0,goddess|marriage ceremony|marriage proposal|pi...,http://www.imdb.com/title/tt0449088/?ref_=fn_t...,1238.0
2,Spectre,275868,11700,Stephanie Sigman,1.0,bomb|espionage|sequel|spy|terrorist,http://www.imdb.com/title/tt2379713/?ref_=fn_t...,994.0
3,The Dark Knight Rises,1144337,106759,Joseph Gordon-Levitt,0.0,deception|imprisonment|lawlessness|police offi...,http://www.imdb.com/title/tt1345836/?ref_=fn_t...,2701.0
4,Star Wars: Episode VII - The Force Awakens ...,8,143,NaN,0.0,NaN,http://www.imdb.com/title/tt5289954/?ref_=fn_t...,NaN

In [22]:
# Muestra 5 filas con las 28 columnas
movies.iloc[0:5]

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

In [24]:
# Muestra los datos de todas las filas de 5 columnas. 
movies.iloc[:,0:5]

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0
1,Color,Gore Verbinski,302.0,169.0,563.0
2,Color,Sam Mendes,602.0,148.0,0.0
3,Color,Christopher Nolan,813.0,164.0,22000.0
4,NaN,Doug Walker,NaN,NaN,131.0
5,Color,Andrew Stanton,462.0,132.0,475.0
6,Color,Sam Raimi,392.0,156.0,0.0
7,Color,Nathan Greno,324.0,100.0,15.0
8,Color,Joss Whedon,635.0,141.0,0.0
9,Color,David Yates,375.0,153.0,282.0
10,Color,Zack Snyder,673.0,183.0,0.0
11,Color,Bryan Singer,434.0,169.0,0.0
12,Color,Marc Forster,403.0,106.0,395.0
13,Color,Gore Verbinski,313.0,151.0,563.0
14,Color,Gore Verbinski,450.0,150.0,563.0
15,Color,Zack Snyder,733.0,143.0,0.0
16,Color,Andrew Adamson,258.0,150.0,80.0
17,Color,Joss Whedon,703.0,173.0,0.0
18,Color,Rob Marshall,448.0,136.0,252.0
19,Color,Barry Sonnenfeld,451.0,106.0,188.0
20,Color,Peter Jackson,422.0,164.0,0.0
21,Color,Marc Webb,599.0,153.0,464.0
22,Color,Ridley Scott,343.0,156.0,0.0
23,Color,Peter Jackson,509.0,186.0,0.0
24,Color,Chris Weitz,251.0,113.0,129.0
25,Color,Peter Jackson,446.0,201.0,0.0
26,Color,James Cameron,315.0,194.0,0.0
27,Color,Anthony Russo,516.0,147.0,94.0
28,Color,Peter Berg,377.0,131.0,532.0
29,Color,Colin Trevorrow,644.0,124.0,365.0
...,...,...,...,...,...
5013,Color,Eric Eason,28.0,79.0,3.0
5014,Color,Uwe Boll,58.0,80.0,892.0
5015,Black and White,Richard Linklater,61.0,100.0,0.0
5016,Color,Joseph Mazzella,NaN,90.0,0.0
5017,Color,Travis Legge,1.0,90.0,138.0
5018,Color,Alex Kendrick,5.0,120.0,589.0
5019,Color,Marcus Nispel,43.0,91.0,158.0
5020,NaN,Brandon Landers,NaN,143.0,8.0
5021,Color,Jay Duplass,51.0,85.0,157.0
5022,Black and White,Jim Chuchu,6.0,60.0,0.0
5023,Color,Daryl Wein,22.0,88.0,38.0
5024,Color,Jason Trost,42.0,78.0,91.0
5025,Color,John Waters,73.0,108.0,0.0
5026,Color,Olivier Assayas,81.0,110.0,107.0
5027,Color,Jafar Panahi,64.0,90.0,397.0
5028,Black and White,Ivan Kavanagh,12.0,83.0,18.0
5029,Color,Kiyoshi Kurosawa,78.0,111.0,62.0
5030,Color,Tadeo Garcia,NaN,84.0,5.0
5031,Color,Thomas L. Phillips,13.0,82.0,120.0
5032,Color,Ash Baron-Cohen,10.0,98.0,3.0
5033,Color,Shane Carruth,143.0,77.0,291.0
5034,Color,Neill Dela Llana,35.0,80.0,0.0
5035,Color,Robert Rodriguez,56.0,81.0,0.0
5036,Color,Anthony Vallone,NaN,84.0,2.0
5037,Color,Edward Burns,14.0,95.0,0.0
5038,Color,Scott Smith,1.0,87.0,2.0
5039,Color,NaN,43.0,43.0,NaN
5040,Color,Benjamin Roberds,13.0,76.0,0.0
5041,Color,Daniel Hsia,14.0,100.0,0.0
5042,Color,Jon Gunn,43.0,90.0,16.0

In [25]:
# ----------------------- Pregunta 3.e ----------------------- 
# Muestra el titulo de las 10 primeras peliculas. 
movies['movie_title'].head(10)

0                                              Avatar
1            Pirates of the Caribbean: At World's End
2                                             Spectre
3                               The Dark Knight Rises
4    Star Wars: Episode VII - The Force Awakens    ...
5                                         John Carter
6                                        Spider-Man 3
7                                             Tangled
8                             Avengers: Age of Ultron
9              Harry Potter and the Half-Blood Prince
Name: movie_title, dtype: object

In [29]:
# Muestra el titulo de las peliculas las 10 primeras filas de esa columna
# en particular.
movies['movie_title'][0:10]

0                                              Avatar
1            Pirates of the Caribbean: At World's End
2                                             Spectre
3                               The Dark Knight Rises
4    Star Wars: Episode VII - The Force Awakens    ...
5                                         John Carter
6                                        Spider-Man 3
7                                             Tangled
8                             Avengers: Age of Ultron
9              Harry Potter and the Half-Blood Prince
Name: movie_title, dtype: object

In [12]:
# Muestra el titulo de la posición 10,11]. 
movies.iloc[0:10,11]

0                                              Avatar
1            Pirates of the Caribbean: At World's End
2                                             Spectre
3                               The Dark Knight Rises
4    Star Wars: Episode VII - The Force Awakens    ...
5                                         John Carter
6                                        Spider-Man 3
7                                             Tangled
8                             Avengers: Age of Ultron
9              Harry Potter and the Half-Blood Prince
Name: movie_title, dtype: object

In [64]:
# ----------------------- EJERCICIO A ----------------------- 
#Número de filas y columnas en el marco de datos de películas
movies['movie_title'].shape

(5043,)

In [26]:
# Muestra el titulo de la pelicula en la posición número 1000 .
movies['movie_title'].iloc[1000]

'Hannibal Rising\xa0'

In [49]:
#Cuántas películas nos faltan datos para el presupuesto de la película.
movies['budget']

0       237000000.0
1       300000000.0
2       245000000.0
3       250000000.0
4               NaN
5       263700000.0
6       258000000.0
7       260000000.0
8       250000000.0
9       250000000.0
10      250000000.0
11      209000000.0
12      200000000.0
13      225000000.0
14      215000000.0
15      225000000.0
16      225000000.0
17      220000000.0
18      250000000.0
19      225000000.0
20      250000000.0
21      230000000.0
22      200000000.0
23      225000000.0
24      180000000.0
25      207000000.0
26      200000000.0
27      250000000.0
28      209000000.0
29      150000000.0
           ...
5013        24000.0
5014            NaN
5015        23000.0
5016        25000.0
5017        22000.0
5018        20000.0
5019            NaN
5020        17350.0
5021        15000.0
5022        15000.0
5023        15000.0
5024        20000.0
5025        10000.0
5026         4500.0
5027        10000.0
5028        10000.0
5029      1000000.0
5030            NaN
5031       200000.0
5032            NaN
5033         7000.0
5034         7000.0
5035         7000.0
5036         3250.0
5037         9000.0
5038            NaN
5039            NaN
5040         1400.0
5041            NaN
5042         1100.0
Name: budget, dtype: float64

In [21]:
# ----------------------- Pregunta 4.a ----------------------- 
#Muestra los nombres de variables de las columnas.
movies.columns.values

array(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes',
       'actor_2_name', 'actor_1_facebook_likes', 'gross', 'genres',
       'actor_1_name', 'movie_title', 'num_voted_users',
       'cast_total_facebook_likes', 'actor_3_name',
       'facenumber_in_poster', 'plot_keywords', 'movie_imdb_link',
       'num_user_for_reviews', 'language', 'country', 'content_rating',
       'budget', 'title_year', 'actor_2_facebook_likes', 'imdb_score',
       'aspect_ratio', 'movie_facebook_likes'], dtype=object)

In [26]:
# ----------------------- Pregunta 4.b.c ----------------------- 
# Muestra los ingresos.
movies['gross'].describe()

count    4.159000e+03
mean     4.846841e+07
std      6.845299e+07
min      1.620000e+02
25%      5.340988e+06
50%      2.551750e+07
75%      6.230944e+07
max      7.605058e+08
Name: gross, dtype: float64

In [79]:
# Valor máximo solo en las columnas numéricas
movies.select_dtypes(include=[np.number]).max()

num_critic_for_reviews       8.130000e+02
duration                     5.110000e+02
director_facebook_likes      2.300000e+04
actor_3_facebook_likes       2.300000e+04
actor_1_facebook_likes       6.400000e+05
gross                        7.605058e+08
num_voted_users              1.689764e+06
cast_total_facebook_likes    6.567300e+05
facenumber_in_poster         4.300000e+01
num_user_for_reviews         5.060000e+03
budget                       1.221550e+10
title_year                   2.016000e+03
actor_2_facebook_likes       1.370000e+05
imdb_score                   9.500000e+00
aspect_ratio                 1.600000e+01
movie_facebook_likes         3.490000e+05
dtype: float64

In [87]:
# ----------------------- EJERCICIO B.1.1 ----------------------- 
#Presupuesto más alto
movies.select_dtypes(include=[np.number])['budget'].max()

12215500000.0

In [91]:
# ----------------------- EJERCICIO B.1.2 ----------------------- 
#Presupuesto promedio
movies.select_dtypes(include=[np.number])['budget'].mean()

39752620.436387606

In [90]:
# ----------------------- EJERCICIO B.1.3 ----------------------- 
#Presupuesto más minimo 
movies.select_dtypes(include=[np.number])['budget'].min()

218.0

In [95]:
# ----------------------- EJERCICIO B.2.1 ----------------------- 
#Puntuacion imdb más altas
movies['imdb_score'].max()

9.5

In [85]:
# ----------------------- EJERCICIO B.2.2 ----------------------- 
#Puntuacion imdb más altas
movies.select_dtypes(include=[np.number])['imdb_score'].min()

1.6000000000000001

In [55]:
#Recuperar rápidamente los recuentos de frecuencia.
movies['title_year'].value_counts()

2009.0    260
2014.0    252
2006.0    239
2013.0    237
2010.0    230
2015.0    226
2011.0    225
2008.0    225
2012.0    221
2005.0    221
2004.0    214
2002.0    209
2007.0    204
2001.0    188
2000.0    171
2003.0    169
1999.0    168
1998.0    134
1997.0    118
2016.0    106
1996.0     99
1995.0     70
1994.0     54
1993.0     48
1992.0     34
1981.0     33
1989.0     33
1987.0     32
1991.0     31
1988.0     31
         ...
1960.0      3
1951.0      3
1948.0      3
1946.0      3
1939.0      3
1959.0      3
1956.0      3
1947.0      3
1955.0      2
1936.0      2
1929.0      2
1949.0      2
1957.0      2
1933.0      2
1937.0      2
1942.0      2
1938.0      2
1941.0      1
1925.0      1
1932.0      1
1920.0      1
1934.0      1
1950.0      1
1943.0      1
1916.0      1
1930.0      1
1944.0      1
1958.0      1
1935.0      1
1927.0      1
Name: title_year, Length: 91, dtype: int64

In [56]:
# ----------------------- Pregunta 5.e -----------------------  
#El año con más frecuencia
movies['title_year'].value_counts(max)

2009.0    0.052685
2014.0    0.051064
2006.0    0.048430
2013.0    0.048024
2010.0    0.046606
2015.0    0.045795
2011.0    0.045593
2008.0    0.045593
2012.0    0.044782
2005.0    0.044782
2004.0    0.043364
2002.0    0.042351
2007.0    0.041337
2001.0    0.038095
2000.0    0.034650
2003.0    0.034245
1999.0    0.034043
1998.0    0.027153
1997.0    0.023911
2016.0    0.021479
1996.0    0.020061
1995.0    0.014184
1994.0    0.010942
1993.0    0.009726
1992.0    0.006890
1981.0    0.006687
1989.0    0.006687
1987.0    0.006484
1991.0    0.006282
1988.0    0.006282
            ...
1960.0    0.000608
1951.0    0.000608
1948.0    0.000608
1946.0    0.000608
1939.0    0.000608
1959.0    0.000608
1956.0    0.000608
1947.0    0.000608
1955.0    0.000405
1936.0    0.000405
1929.0    0.000405
1949.0    0.000405
1957.0    0.000405
1933.0    0.000405
1937.0    0.000405
1942.0    0.000405
1938.0    0.000405
1941.0    0.000203
1925.0    0.000203
1932.0    0.000203
1920.0    0.000203
1934.0    0.000203
1950.0    0.000203
1943.0    0.000203
1916.0    0.000203
1930.0    0.000203
1944.0    0.000203
1958.0    0.000203
1935.0    0.000203
1927.0    0.000203
Name: title_year, Length: 91, dtype: float64

In [57]:
# ----------------------- Pregunta 5.e -----------------------  
#El año con menos frecuencia
movies['title_year'].value_counts(min)

2009.0    0.052685
2014.0    0.051064
2006.0    0.048430
2013.0    0.048024
2010.0    0.046606
2015.0    0.045795
2011.0    0.045593
2008.0    0.045593
2012.0    0.044782
2005.0    0.044782
2004.0    0.043364
2002.0    0.042351
2007.0    0.041337
2001.0    0.038095
2000.0    0.034650
2003.0    0.034245
1999.0    0.034043
1998.0    0.027153
1997.0    0.023911
2016.0    0.021479
1996.0    0.020061
1995.0    0.014184
1994.0    0.010942
1993.0    0.009726
1992.0    0.006890
1981.0    0.006687
1989.0    0.006687
1987.0    0.006484
1991.0    0.006282
1988.0    0.006282
            ...
1960.0    0.000608
1951.0    0.000608
1948.0    0.000608
1946.0    0.000608
1939.0    0.000608
1959.0    0.000608
1956.0    0.000608
1947.0    0.000608
1955.0    0.000405
1936.0    0.000405
1929.0    0.000405
1949.0    0.000405
1957.0    0.000405
1933.0    0.000405
1937.0    0.000405
1942.0    0.000405
1938.0    0.000405
1941.0    0.000203
1925.0    0.000203
1932.0    0.000203
1920.0    0.000203
1934.0    0.000203
1950.0    0.000203
1943.0    0.000203
1916.0    0.000203
1930.0    0.000203
1944.0    0.000203
1958.0    0.000203
1935.0    0.000203
1927.0    0.000203
Name: title_year, Length: 91, dtype: float64

In [11]:
# ----------------------- Pregunta 6 -----------------------  
# Muestra de forma ordenada el marco del presupuesto.
movies.sort_values('gross')

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
3330,Color,Ekachai Uekrongtham,66.0,96.0,3.0,305.0,Mike Dopud,2000.0,162.0,Action|Crime|Thriller,...,38.0,English,Thailand,R,9000000.0,2014.0,368.0,5.7,2.35,0
4607,Color,Frank Whaley,9.0,96.0,436.0,4.0,Frank Whaley,474.0,703.0,Comedy|Drama,...,21.0,English,USA,R,1500000.0,2001.0,436.0,5.4,1.85,47
4606,Color,Brian Trenchard-Smith,8.0,88.0,53.0,176.0,Mariel Hemingway,563.0,721.0,Action|Drama,...,12.0,English,Germany,R,1000000.0,2006.0,288.0,4.1,1.85,42
3840,Color,Robert Sarkies,43.0,100.0,0.0,3.0,Matthew Sunderland,109.0,728.0,Crime|Drama,...,22.0,English,New Zealand,NaN,NaN,2006.0,10.0,7.3,1.85,285
3552,Color,Ian Fitzgibbon,54.0,88.0,11.0,415.0,Brendan Coyle,1000.0,828.0,Action|Comedy|Crime|Drama|Romance|Thriller,...,31.0,English,Ireland,R,NaN,2009.0,418.0,6.4,2.35,663
4915,Color,Ricki Stern,11.0,106.0,15.0,0.0,Evelyn Jefferson,2.0,1111.0,Crime|Documentary,...,10.0,English,USA,PG-13,200000.0,2006.0,0.0,7.7,1.66,246
4758,Color,Alex Craig Mann,29.0,87.0,38.0,445.0,Christa B. Allen,552.0,1332.0,Comedy|Horror,...,20.0,English,USA,Not Rated,500000.0,2012.0,533.0,4.6,2.35,898
4465,Color,Boris Rodriguez,56.0,83.0,5.0,98.0,Thure Lindhardt,413.0,1521.0,Comedy|Horror,...,10.0,English,Canada,Not Rated,1500000.0,2012.0,197.0,5.7,NaN,932
4843,Color,John D. Hancock,4.0,110.0,44.0,221.0,Elizabeth Stenholt,644.0,1711.0,Drama|Music,...,1.0,English,USA,NaN,NaN,2015.0,503.0,6.6,NaN,175
4720,Color,U. Roberto Romano,3.0,80.0,6.0,NaN,NaN,NaN,2245.0,Documentary,...,2.0,English,USA,NaN,560000.0,2011.0,NaN,7.2,NaN,88
4333,Black and White,Paul Bunnell,94.0,106.0,5.0,356.0,Kevin McCarthy,416.0,2436.0,Comedy|Fantasy|Musical|Sci-Fi,...,19.0,English,USA,Not Rated,2000000.0,2012.0,403.0,5.7,2.35,655
4845,Color,Bruce Dellis,10.0,95.0,0.0,309.0,Ricky Schroder,685.0,2468.0,Thriller,...,5.0,English,USA,R,300000.0,2014.0,665.0,4.8,1.85,261
4399,Color,Adam Goldberg,22.0,111.0,1000.0,127.0,Marisa Coughlan,2000.0,2580.0,Drama|Mystery,...,40.0,English,USA,R,1650000.0,2003.0,163.0,5.4,2.35,63
4316,Color,Catherine Hardwicke,18.0,99.0,308.0,395.0,James Kyson,638.0,2843.0,Thriller,...,24.0,English,USA,R,NaN,2013.0,449.0,5.4,1.78,604
3321,Color,André Téchiné,66.0,105.0,25.0,98.0,Ronit Elkabetz,963.0,2874.0,Drama,...,14.0,French,France,Unrated,NaN,2009.0,168.0,6.0,2.35,120
2589,Color,Amy Heckerling,54.0,92.0,143.0,613.0,Justin Kirk,1000.0,2964.0,Comedy|Horror|Romance,...,42.0,English,USA,PG-13,16000000.0,2012.0,945.0,5.1,1.78,0
4241,Color,Robert Fontaine,4.0,125.0,7.0,17.0,Arturo Castro,128.0,3330.0,Crime|Drama,...,1.0,English,USA,R,2100000.0,2015.0,22.0,7.2,2.35,305
4434,Color,Bruce McDonald,178.0,95.0,49.0,57.0,Georgina Reilly,413.0,3478.0,Fantasy|Horror,...,142.0,English,Canada,Not Rated,1500000.0,2008.0,98.0,6.7,2.35,0
3242,Color,Álex de la Iglesia,71.0,104.0,275.0,102.0,Leonor Watling,439.0,3607.0,Crime|Mystery|Thriller,...,94.0,English,Spain,R,10000000.0,2008.0,161.0,6.1,2.35,0
4505,Color,Tom Sanchez,1.0,110.0,0.0,0.0,Antonio Arrué,3.0,3830.0,Comedy|Drama,...,1.0,Spanish,USA,NaN,1200000.0,2013.0,2.0,7.2,NaN,75
3959,Color,Ruba Nadda,36.0,93.0,55.0,5.0,Bonnie Lee Bouman,223.0,4063.0,Drama|Mystery|Romance|Thriller,...,20.0,English,Canada,R,4000000.0,2012.0,11.0,5.2,2.35,657
1527,Color,Jeremy Degruson,60.0,85.0,0.0,11.0,Brianne Brozey,324.0,4091.0,Adventure|Animation|Comedy|Family|Fantasy,...,16.0,English,Belgium,NaN,34000000.0,2013.0,15.0,6.3,2.35,0
4334,Color,Phil Morrison,41.0,107.0,17.0,322.0,Curtiss Cook,594.0,4556.0,Comedy|Drama,...,23.0,English,USA,R,NaN,2013.0,591.0,5.6,NaN,825
5037,Color,Edward Burns,14.0,95.0,0.0,133.0,Caitlin FitzGerald,296.0,4584.0,Comedy|Drama,...,14.0,English,USA,Not Rated,9000.0,2011.0,205.0,6.4,NaN,413
2061,Color,Jonathan Newman,28.0,100.0,3.0,88.0,Keeley Hawes,2000.0,4756.0,Adventure|Family|Fantasy,...,32.0,English,UK,PG,25000000.0,2013.0,228.0,5.4,2.35,0
4938,Color,Dena Seidel,5.0,72.0,0.0,0.0,Hugh Ducklow,0.0,4914.0,Adventure|Documentary,...,2.0,English,USA,NaN,150000.0,2015.0,0.0,7.0,NaN,215
4318,Color,Ralph Ziman,30.0,119.0,5.0,12.0,Kenneth Nkosi,29.0,4958.0,Action|Crime|Drama,...,23.0,English,South Africa,R,2000000.0,2008.0,18.0,7.8,2.35,1000
4130,Color,Francesca Gregorini,21.0,96.0,15.0,357.0,Amy Sedaris,433.0,5005.0,Drama,...,14.0,English,USA,R,3000000.0,2009.0,396.0,5.9,NaN,448
4840,Color,Eddie O'Flaherty,13.0,109.0,3.0,25.0,Eddie Jones,54.0,5199.0,Drama|Sport,...,23.0,English,USA,R,200000.0,2004.0,53.0,6.6,2.35,30
4604,Color,Darren Stein,8.0,90.0,18.0,422.0,Jamie Kennedy,491.0,5494.0,Comedy|Drama,...,13.0,English,USA,R,NaN,1997.0,490.0,5.6,NaN,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4990,Color,Jem Cohen,12.0,111.0,6.0,NaN,NaN,NaN,NaN,Documentary,...,1.0,English,USA,NaN,50000.0,2015.0,NaN,6.0,1.78,5
4991,Black and White,Andrew Leman,60.0,47.0,2.0,5.0,David Mersault,19.0,NaN,Fantasy|Horror|Mystery|Thriller,...,99.0,English,USA,NaN,50000.0,2005.0,9.0,7.3,1.33,0
4992,Color,Dave Carroll,10.0,92.0,0.0,NaN,NaN,0.0,NaN,Documentary,...,10.0,English,USA,NaN,50000.0,2013.0,NaN,7.9,16.00,33
4993,Color,William Eubank,161.0,97.0,18.0,236.0,Olivia Cooke,852.0,NaN,Sci-Fi|Thriller,...,180.0,English,USA,PG-13,4000000.0,2014.0,680.0,6.1,2.35,10000
4994,Color,Patrick Meaney,7.0,81.0,3.0,18.0,Greg Aronowitz,26.0,NaN,Biography|Documentary,...,2.0,English,USA,NaN,50000.0,2014.0,20.0,7.4,NaN,83
4995,Color,Chad Hartigan,34.0,83.0,3.0,69.0,Paul Eenhoorn,695.0,NaN,Drama,...,7.0,English,USA,R,42000.0,2013.0,571.0,6.6,16.00,234
4996,Color,Malcolm Goodwin,NaN,96.0,117.0,281.0,Jon Gries,948.0,NaN,Comedy,...,4.0,English,USA,NaN,45000.0,2013.0,482.0,5.5,2.35,72
4999,Color,Kirk Loudon,3.0,95.0,0.0,279.0,Johnny Walter,883.0,NaN,Drama|Sci-Fi|Thriller,...,2.0,English,USA,NaN,75000.0,2014.0,507.0,5.0,NaN,87
5000,Color,Travis Legge,2.0,83.0,138.0,76.0,Patricia Raven,307.0,NaN,Horror,...,6.0,English,USA,Unrated,40000.0,2011.0,114.0,3.2,2.35,239
5002,Color,Collin Joseph Neal,7.0,75.0,14.0,130.0,Thomas Brophy,252.0,NaN,Horror|Thriller,...,5.0,English,USA,NaN,50000.0,2012.0,132.0,3.7,2.35,225
5005,Black and White,Andrew Bujalski,52.0,109.0,26.0,3.0,Kate Dollenmayer,26.0,NaN,Comedy,...,23.0,English,USA,R,NaN,2005.0,6.0,6.9,1.66,91
5006,Color,Damir Catic,NaN,89.0,2.0,0.0,Ron Gelner,5.0,NaN,Horror,...,2.0,English,USA,Not Rated,60000.0,2013.0,0.0,5.4,NaN,48
5010,Color,Andrew Bujalski,43.0,85.0,26.0,3.0,Kate Dollenmayer,26.0,NaN,Comedy|Drama,...,61.0,English,USA,NaN,NaN,2002.0,6.0,6.4,1.37,108
5013,Color,Eric Eason,28.0,79.0,3.0,42.0,Panchito Gómez,93.0,NaN,Drama|Family,...,21.0,English,USA,NaN,24000.0,2002.0,46.0,7.0,1.78,61
5014,Color,Uwe Boll,58.0,80.0,892.0,492.0,Katharine Isabelle,986.0,NaN,Action|Crime|Thriller,...,129.0,English,Canada,R,NaN,2009.0,918.0,6.3,2.35,0
5016,Color,Joseph Mazzella,NaN,90.0,0.0,9.0,Mikaal Bates,313.0,NaN,Crime|Drama|Thriller,...,2.0,English,USA,NaN,25000.0,2015.0,25.0,4.8,NaN,33
5017,Color,Travis Legge,1.0,90.0,138.0,138.0,Suzi Lorraine,370.0,NaN,Comedy|Romance,...,3.0,English,USA,NaN,22000.0,2013.0,184.0,3.3,1.78,200
5018,Color,Alex Kendrick,5.0,120.0,589.0,4.0,Lisa Arnold,51.0,NaN,Drama,...,49.0,English,USA,NaN,20000.0,2003.0,49.0,6.9,1.85,725
5019,Color,Marcus Nispel,43.0,91.0,158.0,265.0,Brittany Curran,630.0,NaN,Horror|Mystery|Thriller,...,33.0,English,USA,R,NaN,2015.0,512.0,4.6,1.85,0
5020,NaN,Brandon Landers,NaN,143.0,8.0,8.0,Alana Kaniewski,720.0,NaN,Drama|Horror|Thriller,...,8.0,English,USA,NaN,17350.0,2011.0,19.0,3.0,NaN,33
5022,Black and White,Jim Chuchu,6.0,60.0,0.0,4.0,Olwenya Maina,147.0,NaN,Drama,...,1.0,Swahili,Kenya,NaN,15000.0,2014.0,19.0,7.4,NaN,45
5024,Color,Jason Trost,42.0,78.0,91.0,86.0,Jason Trost,407.0,NaN,Sci-Fi|Thriller,...,35.0,English,USA,Unrated,20000.0,2011.0,91.0,4.0,2.35,835
5028,Black and White,Ivan Kavanagh,12.0,83.0,18.0,0.0,Michael Parle,10.0,NaN,Horror,...,1.0,English,Ireland,NaN,10000.0,2007.0,5.0,6.7,1.33,105
5030,Color,Tadeo Garcia,NaN,84.0,5.0,12.0,Michael Cortez,21.0,NaN,Drama,...,3.0,English,USA,NaN,NaN,2004.0,20.0,6.1,NaN,22
5031,Color,Thomas L. Phillips,13.0,82.0,120.0,84.0,Joe Coffey,785.0,NaN,Comedy|Horror|Thriller,...,8.0,English,USA,NaN,200000.0,2012.0,98.0,5.4,16.00,424
5032,Color,Ash Baron-Cohen,10.0,98.0,3.0,152.0,Stanley B. Herman,789.0,NaN,Crime|Drama,...,14.0,English,USA,NaN,NaN,1995.0,194.0,6.4,NaN,20
5036,Color,Anthony Vallone,NaN,84.0,2.0,2.0,John Considine,45.0,NaN,Crime|Drama,...,1.0,English,USA,PG-13,3250.0,2005.0,44.0,7.8,NaN,4
5038,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
5039,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
5040,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16

In [12]:
# ----------------------- Pregunta 7 -----------------------  
# Al hacer el ejercicio anterior se pueden modificar los datos ya que l
# lo primero que hace es regresar datos pero sin guardar el marco nuevo
# y clasifica las peliculas en orden ascendente.
# Por ello se utiliza lo siguiente para solucionarlo
topgrossing=movies.sort_values('gross',ascending=False)

In [66]:
# ----------------------- Pregunta 8.a Aclaracion  -----------------------  
# movies. Es el marco de datos
# sort_values() Ordena un marco de datos en función de los valores en una columna específica
# ('gross' Especifica que estamos ordenando según la columna titulada "gross".  
# ,ascending=False)  Ordene en orden descendente.
# "topgrossing" El nuevo nombre del marco.

In [13]:
# ----------------------- Pregunta 9 -----------------------  
# Las 25 peliculas más taquilleras.
topgrossing.head(25)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
26,Color,James Cameron,315.0,194.0,0.0,794.0,Kate Winslet,29000.0,658672302.0,Drama|Romance,...,2528.0,English,USA,PG-13,200000000.0,1997.0,14000.0,7.7,2.35,26000
29,Color,Colin Trevorrow,644.0,124.0,365.0,1000.0,Judy Greer,3000.0,652177271.0,Action|Adventure|Sci-Fi|Thriller,...,1290.0,English,USA,PG-13,150000000.0,2015.0,2000.0,7.0,2.00,150000
794,Color,Joss Whedon,703.0,173.0,0.0,19000.0,Robert Downey Jr.,26000.0,623279547.0,Action|Adventure|Sci-Fi,...,1722.0,English,USA,PG-13,220000000.0,2012.0,21000.0,8.1,1.85,123000
17,Color,Joss Whedon,703.0,173.0,0.0,19000.0,Robert Downey Jr.,26000.0,623279547.0,Action|Adventure|Sci-Fi,...,1722.0,English,USA,PG-13,220000000.0,2012.0,21000.0,8.1,1.85,123000
66,Color,Christopher Nolan,645.0,152.0,22000.0,11000.0,Heath Ledger,23000.0,533316061.0,Action|Crime|Drama|Thriller,...,4667.0,English,USA,PG-13,185000000.0,2008.0,13000.0,9.0,2.35,37000
240,Color,George Lucas,320.0,136.0,0.0,1000.0,Liam Neeson,20000.0,474544677.0,Action|Adventure|Fantasy|Sci-Fi,...,3597.0,English,USA,PG,115000000.0,1999.0,14000.0,6.5,2.35,13000
3024,Color,George Lucas,282.0,125.0,0.0,504.0,Peter Cushing,11000.0,460935665.0,Action|Adventure|Fantasy|Sci-Fi,...,1470.0,English,USA,PG,11000000.0,1977.0,1000.0,8.7,2.35,33000
8,Color,Joss Whedon,635.0,141.0,0.0,19000.0,Robert Downey Jr.,26000.0,458991599.0,Action|Adventure|Sci-Fi,...,1117.0,English,USA,PG-13,250000000.0,2015.0,21000.0,7.5,2.35,118000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
582,Color,Andrew Adamson,205.0,93.0,80.0,48.0,Jennifer Saunders,692.0,436471036.0,Adventure|Animation|Comedy|Family|Fantasy|Romance,...,483.0,English,USA,PG,150000000.0,2004.0,309.0,7.2,1.85,0
3080,Color,Steven Spielberg,215.0,120.0,14000.0,548.0,Dee Wallace,861.0,434949459.0,Family|Sci-Fi,...,515.0,English,USA,PG,10500000.0,1982.0,725.0,7.9,1.85,34000
186,Color,Francis Lawrence,502.0,146.0,508.0,523.0,Josh Hutcherson,34000.0,424645577.0,Adventure|Sci-Fi|Thriller,...,706.0,English,USA,PG-13,130000000.0,2013.0,14000.0,7.6,2.35,82000
13,Color,Gore Verbinski,313.0,151.0,563.0,1000.0,Orlando Bloom,40000.0,423032628.0,Action|Adventure|Fantasy,...,1832.0,English,USA,PG-13,225000000.0,2006.0,5000.0,7.3,2.35,5000
509,Color,Roger Allers,186.0,73.0,28.0,847.0,Nathan Lane,2000.0,422783777.0,Adventure|Animation|Drama|Family|Musical,...,656.0,English,USA,G,45000000.0,1994.0,886.0,8.5,1.66,17000
43,Color,Lee Unkrich,453.0,103.0,125.0,721.0,John Ratzenberger,15000.0,414984497.0,Adventure|Animation|Comedy|Family|Fantasy,...,733.0,English,USA,G,200000000.0,2010.0,1000.0,8.3,1.85,30000
32,Color,Shane Black,608.0,195.0,1000.0,3000.0,Jon Favreau,21000.0,408992272.0,Action|Adventure|Sci-Fi,...,1187.0,English,USA,PG-13,200000000.0,2013.0,4000.0,7.2,2.35,95000
439,Color,Gary Ross,673.0,142.0,378.0,575.0,Josh Hutcherson,34000.0,407999255.0,Adventure|Drama|Sci-Fi|Thriller,...,1959.0,English,USA,PG-13,78000000.0,2012.0,14000.0,7.3,2.35,140000
27,Color,Anthony Russo,516.0,147.0,94.0,11000.0,Scarlett Johansson,21000.0,407197282.0,Action|Adventure|Sci-Fi,...,1022.0,English,USA,PG-13,250000000.0,2016.0,19000.0,8.2,2.35,72000
161,Color,Sam Raimi,291.0,121.0,0.0,4000.0,James Franco,24000.0,403706375.0,Action|Adventure|Fantasy|Romance,...,2012.0,English,USA,PG-13,139000000.0,2002.0,11000.0,7.3,1.85,5000
36,Color,Michael Bay,366.0,150.0,0.0,464.0,Kevin Dunn,894.0,402076689.0,Action|Adventure|Sci-Fi,...,1439.0,English,USA,PG-13,200000000.0,2009.0,581.0,6.0,2.35,0
125,Color,Chris Buck,406.0,102.0,69.0,490.0,Maurice LaMarche,1000.0,400736600.0,Adventure|Animation|Comedy|Family|Fantasy|Musical,...,904.0,English,USA,PG,150000000.0,2013.0,523.0,7.6,2.24,58000
338,Color,Andrew Stanton,301.0,100.0,475.0,799.0,Stephen Root,1000.0,380838870.0,Adventure|Animation|Comedy|Family,...,866.0,English,USA,G,94000000.0,2003.0,939.0,8.2,1.85,11000
236,Color,George Lucas,359.0,140.0,0.0,4000.0,Christopher Lee,20000.0,380262555.0,Action|Adventure|Fantasy|Sci-Fi,...,3286.0,English,USA,PG-13,113000000.0,2005.0,16000.0,7.6,2.35,10000
339,Color,Peter Jackson,328.0,192.0,0.0,416.0,Billy Boyd,5000.0,377019252.0,Action|Adventure|Drama|Fantasy,...,3189.0,English,USA,PG-13,94000000.0,2003.0,857.0,8.9,2.35,16000

In [14]:
# ----------------------- Pregunta 10 -----------------------  
# Cambia los datos para que imprima el titulo, el año y el primer 
# actor de las peliculas.
topgrossing2=topgrossing[['movie_title','title_year','actor_1_name']]

In [15]:
# ----------------------- Pregunta 11 -----------------------  
# Las 25 peliculas más taquilleras especifica utilizando el un nuevo marco
# topgrossing2.
topgrossing2.head(25)

,movie_title,title_year,actor_1_name
0,Avatar,2009.0,CCH Pounder
26,Titanic,1997.0,Leonardo DiCaprio
29,Jurassic World,2015.0,Bryce Dallas Howard
794,The Avengers,2012.0,Chris Hemsworth
17,The Avengers,2012.0,Chris Hemsworth
66,The Dark Knight,2008.0,Christian Bale
240,Star Wars: Episode I - The Phantom Menace,1999.0,Natalie Portman
3024,Star Wars: Episode IV - A New Hope,1977.0,Harrison Ford
8,Avengers: Age of Ultron,2015.0,Chris Hemsworth
3,The Dark Knight Rises,2012.0,Tom Hardy
582,Shrek 2,2004.0,Rupert Everett
3080,E.T. the Extra-Terrestrial,1982.0,Henry Thomas
186,The Hunger Games: Catching Fire,2013.0,Jennifer Lawrence
13,Pirates of the Caribbean: Dead Man's Chest,2006.0,Johnny Depp
509,The Lion King,1994.0,Matthew Broderick
43,Toy Story 3,2010.0,Tom Hanks
32,Iron Man 3,2013.0,Robert Downey Jr.
439,The Hunger Games,2012.0,Jennifer Lawrence
27,Captain America: Civil War,2016.0,Robert Downey Jr.
161,Spider-Man,2002.0,J.K. Simmons
36,Transformers: Revenge of the Fallen,2009.0,Glenn Morshower
125,Frozen,2013.0,Josh Gad
338,Finding Nemo,2003.0,Alexander Gould
236,Star Wars: Episode III - Revenge of the Sith,2005.0,Natalie Portman
339,The Lord of the Rings: The Return of the King,2003.0,Orlando Bloom

In [7]:
# ----------------------- EJERCICIO C.1 ----------------------- 
# Crear marco
movies.sort_values('imdb_score')
# Soluciona los problemas de asendencia.
topimbd_score=movies.sort_values('imdb_score',ascending=False)
# Filtro los datos para que imprima solo el ítulo de la película, el año, 
# el presupuesto y la puntuación imdb.
topimbd_score2=topimbd_score[
    ['movie_title','title_year','budget','imdb_score']]

In [31]:
#1 Resultado las 15 películas mejor calificadas en el conjunto de datos
#  por puntaje imdb.
topimbd_score2.head(15)

,movie_title,title_year,budget,imdb_score
2765,Towering Inferno,NaN,NaN,9.5
1937,The Shawshank Redemption,1994.0,25000000.0,9.3
3466,The Godfather,1972.0,6000000.0,9.2
4409,Kickboxer: Vengeance,2016.0,17000000.0,9.1
2824,Dekalog,NaN,NaN,9.1
3207,Dekalog,NaN,NaN,9.1
66,The Dark Knight,2008.0,185000000.0,9.0
2837,The Godfather: Part II,1974.0,13000000.0,9.0
3481,Fargo,NaN,NaN,9.0
339,The Lord of the Rings: The Return of the King,2003.0,94000000.0,8.9
4822,12 Angry Men,1957.0,350000.0,8.9
4498,"The Good, the Bad and the Ugly",1966.0,1200000.0,8.9
3355,Pulp Fiction,1994.0,8000000.0,8.9
1874,Schindler's List,1993.0,22000000.0,8.9
683,Fight Club,1999.0,63000000.0,8.8

In [20]:
# ----------------------- Pregunta 12  ----------------------
#Creacion de una nueva columna de los datos de presupuesto e ingresos
# de las peliculas, la cual es para  para calcular los ingresos netos. 
movies['net_profit']=movies['gross'] - movies['budget']

In [21]:
# ----------------------- Pregunta 13  ----------------------
# Muestra las 5 primeras entradas de la columna creada net_profit. 
movies['net_profit'].head()

0    523505847.0
1      9404152.0
2    -44925825.0
3    198130642.0
4            NaN
Name: net_profit, dtype: float64

In [22]:
# ----------------------- Pregunta 14  ----------------------
# 
mostprofit=movies.sort_values('net_profit',ascending=False)
mostprofit['movie_title'].head(20)

0                                              Avatar
29                                     Jurassic World
26                                            Titanic
3024               Star Wars: Episode IV - A New Hope
3080                       E.T. the Extra-Terrestrial
794                                      The Avengers
17                                       The Avengers
509                                     The Lion King
240         Star Wars: Episode I - The Phantom Menace
66                                    The Dark Knight
439                                  The Hunger Games
812                                          Deadpool
186                   The Hunger Games: Catching Fire
697                                     Jurassic Park
521                                   Despicable Me 2
814                                   American Sniper
338                                      Finding Nemo
582                                           Shrek 2
339     The Lord of the Rings: The Return of the King
1536       Star Wars: Episode VI - Return of the Jedi
Name: movie_title, dtype: object

In [51]:
# ----------------------- EJERCICIO D  ----------------------
# las 10 peliculas mas alquiladas

In [98]:
# ----------------------- Pregunta 15  ----------------------
# Filtro de peliculas por año.
after2000=movies[movies['title_year']>2000]

In [99]:
# ----------------------- Pregunta 16 ----------------------- 
# Crear marco
movies.sort_values('movie_title')
# Soluciona los problemas de asendencia.
topmovies_score=movies.sort_values('movie_title',ascending=False)
# Filtro los datos para que imprima solo el ítulo de la película, el año, 
# el presupuesto y la puntuación imdb.
topmovies_score2=topimbd_score[['movie_title','title_year']]
topmovies_score2.head()

                        movie_title  title_year
2765  Towering Inferno                      NaN
1937      The Shawshank Redemption       1994.0
3466                 The Godfather       1972.0
4409          Kickboxer: Vengeance       2016.0
2824           Dekalog                      NaN

In [85]:
# ----------------------- Ejercicio E  ----------------------
# Filtro de peliculas por año.
after1960=movies[movies['title_year']>1960]

In [84]:
movies.sort_values('movie_title')
# Soluciona los problemas de asendencia.
topmovie60_score=movies.sort_values('movie_title',ascending=False)
# Filtro los datos para que imprima solo el ítulo de la película, el año, 
# el presupuesto y la puntuación imdb.
topmovie60_score2=topmovie60_score[['movie_title','title_year']]
topmovie60_score2.head()

                   movie_title  title_year
882                  Æon Flux       2005.0
585                       xXx       2002.0
790   xXx: State of the Union       2005.0
2151                 eXistenZ       1999.0
4242                    [Rec]       2007.0

In [ ]:
<